"""Run the macro barometer vector over telemetry-defined generic indices.

The generic watchlist is produced from ``data/telemetry_list.txt``.  This
module deliberately derives its index universe from the ``[INDEX_PAIRS]``
section instead of maintaining a second hard-coded list, so adding an eighth,
ninth, or tenth index remains a configuration-only change.
"""

from __future__ import annotations

import argparse
import re
from datetime import datetime
from pathlib import Path

import pandas as pd

from obv5_signal_engine import run_obv5_signal_engine


PROJECT_DIR = Path(__file__).resolve().parents[1]
TELEMETRY_PATH = PROJECT_DIR / "data" / "telemetry_list.txt"
GENERIC_WATCHLIST_DIR = PROJECT_DIR / "data" / "sanitized_watchlists"
FUNDAMENTAL_OUTPUT_DIR = PROJECT_DIR / "output" / "fundemental_matrix"
OBV5_OUTPUT_DIR = PROJECT_DIR / "output" / "obv5_engine"


def telemetry_index_symbols(config_path: Path = TELEMETRY_PATH) -> list[str]:
    """Return unique symbols declared under ``[INDEX_PAIRS]`` in order."""
    if not config_path.exists():
        return []

    symbols: list[str] = []
    section = None
    for line in config_path.read_text(encoding="utf-8").splitlines():
        value = line.strip()
        if not value or value.startswith("#"):
            continue
        if value.startswith("[") and value.endswith("]"):
            section = value.upper()
            continue
        if section != "[INDEX_PAIRS]":
            continue
        for token in value.split(","):
            symbol = token.strip().strip('"').strip("'").replace("\\n", "").strip().upper()
            if symbol and symbol not in symbols:
                symbols.append(symbol)
    return symbols


def latest_generic_watchlist(
    watchlist_dir: Path = GENERIC_WATCHLIST_DIR,
) -> Path | None:
    """Locate the newest sanitized generic watchlist generated by processor."""
    candidates = sorted(
        path for path in watchlist_dir.glob("*-watchlist-generic_SANITIZED.csv")
        if re.match(r"^\d{4}-\d{2}-\d{2}-watchlist-generic_SANITIZED\.csv$", path.name)
    )
    return candidates[-1] if candidates else None


def generic_index_symbols(
    index_symbols: list[str],
    watchlist_path: Path | None = None,
) -> list[str]:
    """Select telemetry indices from the processor's generic watchlist.

    The symbol match is authoritative; row order is retained for stable
    vectors, and ``Source_Watchlists`` is checked when the column exists.
    """
    path = watchlist_path or latest_generic_watchlist()
    if path is None or not index_symbols:
        return []

    frame = pd.read_csv(path, usecols=lambda column: column in {"Symbol", "Source_Watchlists"})
    if "Symbol" not in frame.columns:
        return []
    if "Source_Watchlists" in frame.columns:
        generic_rows = frame[frame["Source_Watchlists"].astype(str).str.lower() == "generic"]
    else:
        generic_rows = frame

    requested = {symbol.upper() for symbol in index_symbols}
    selected: list[str] = []
    for raw_symbol in generic_rows["Symbol"].dropna():
        symbol = str(raw_symbol).strip().upper()
        if symbol in requested and symbol not in selected:
            selected.append(symbol)
    return selected


def fundamental_candidate_symbols(
    candidate_scope: str = "none",
    profile: str = "base",
    limit: int = 20,
    output_dir: Path = FUNDAMENTAL_OUTPUT_DIR,
) -> list[str]:
    """Read unique long/short symbols from the newest profile candidate outputs."""
    if candidate_scope not in {"none", "long", "short", "both"}:
        raise ValueError("candidate_scope must be none, long, short, or both")
    if limit < 0:
        raise ValueError("limit must be zero or greater")
    if candidate_scope == "none" or not output_dir.exists():
        return []

    suffixes = {
        "long": ("_FUNDAMENTAL_QUALIFIED_LONG.csv",),
        "short": ("_FUNDAMENTAL_QUALIFIED_SHORT.csv",),
        "both": (
            "_FUNDAMENTAL_QUALIFIED_LONG.csv",
            "_FUNDAMENTAL_QUALIFIED_SHORT.csv",
        ),
    }[candidate_scope]
    dated_files: list[tuple[str, Path]] = []
    for suffix in suffixes:
        profile_suffix = f"_{profile.upper()}{suffix}"
        for path in output_dir.glob(f"*{profile_suffix}"):
            match = re.match(r"^(\d{4}-\d{2}-\d{2})", path.name)
            if match:
                dated_files.append((match.group(1), path))
    if not dated_files:
        return []

    latest_date = max(date for date, _ in dated_files)
    symbols: list[str] = []
    for date, path in sorted(dated_files, key=lambda item: item[1].name):
        if date != latest_date:
            continue
        try:
            frame = pd.read_csv(path, usecols=["Symbol"])
        except (OSError, ValueError, pd.errors.ParserError):
            continue
        selected_rows = frame["Symbol"].dropna()
        if limit:
            selected_rows = selected_rows.iloc[:limit]
        for raw_symbol in selected_rows:
            symbol = str(raw_symbol).strip().upper()
            if symbol and symbol not in symbols:
                symbols.append(symbol)
    return symbols


def obv5_hit_symbols(
    variant: str = "none",
    output_dir: Path = OBV5_OUTPUT_DIR,
) -> list[str]:
    """Read unique symbols from the newest OBV5 latest-three-bar hits variant."""
    if variant not in {"none", "p4_all", "p5_ext", "p5_all"}:
        raise ValueError("variant must be none, p4_all, p5_ext, or p5_all")
    if variant == "none" or not output_dir.exists():
        return []
    candidates = sorted(output_dir.glob(f"*_OBV5_LATEST3_HITS_{variant.upper()}_*.csv"))
    if not candidates:
        return []
    try:
        frame = pd.read_csv(candidates[-1], usecols=["Symbol"])
    except (OSError, ValueError, pd.errors.ParserError):
        return []
    symbols: list[str] = []
    for raw_symbol in frame["Symbol"].dropna():
        symbol = str(raw_symbol).strip().upper()
        if symbol and symbol not in symbols:
            symbols.append(symbol)
    return symbols


def run_macro_barometer_vector(
    data_source: str = "local",
    watchlist_path: Path | None = None,
    telemetry_path: Path = TELEMETRY_PATH,
    **engine_options,
) -> pd.DataFrame:
    """Generate OBV5 signals for the telemetry-defined generic index vector."""
    configured = telemetry_index_symbols(telemetry_path)
    selected = generic_index_symbols(configured, watchlist_path)
    if not selected:
        # A generic file may not exist before the processor's first run. The
        # config remains the canonical universe for that bootstrap case.
        selected = configured

    print(f"📡 Macro vector source: {len(selected)} telemetry indices")
    print(f"   {' | '.join(selected) if selected else 'No index symbols found'}")
    return run_obv5_signal_engine(
        symbols=selected,
        data_source=data_source,
        **engine_options,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Macro barometer vector for generic telemetry indices")
    parser.add_argument("--data-source", choices=("local", "auto", "online"), default="local")
    parser.add_argument("--generic-watchlist", type=Path, default=None)
    parser.add_argument("--shift", type=int, default=0)
    parser.add_argument("--detailed", type=int, choices=(0, 1), default=1)
    parser.add_argument("--recent-bars", type=int, default=20)
    args = parser.parse_args()

    run_macro_barometer_vector(
        data_source=args.data_source,
        watchlist_path=args.generic_watchlist,
        shift_bars=args.shift,
        detailed=args.detailed == 1,
        recent_bars=args.recent_bars,
    )


if __name__ == "__main__":
    main()